// ─── Types ───────────────────────────────────────────────────────────────────
//
// The catalog is fully bilingual (Polish is the primary locale, English is
// secondary). Translated fields use `LocalizedString` from the i18n module so
// they carry both languages side-by-side. The view layer resolves them to a
// plain string at render time via the `useCatalog` hooks (see ./useCatalog.ts).
//
// Fields that stay as plain strings:
//   • `name`      — brand-style names (e.g. "Sukienka Monaco") read the same in
//                   both languages and are part of the brand's visual identity.
//   • `collection.name` — city names: Monaco, Paris, New York… locale-neutral.
//   • `blog.author`     — "Absolut Dimension" — a name, not a translation.
//
// Everything else that a user can read on the page is bilingual.

import type { LocalizedString } from "../i18n";
import { blogBodies, type BlogBlock } from "./blog-bodies";
import { generatedCollections, generatedProducts } from "./catalog.generated";

export type { BlogBlock };

export type ProductCategory =
  | "dress"
  | "coat"
  | "bag"
  | "set"
  | "skirt"
  | "top"
  | "blazer"
  | "kimono"
  | "scarf"
  | "pants"
  | "cardigan"
  | "poncho"
  | "body"
  | "blouse";

export interface Product {
  id: string;
  name: string;
  price: number; // in PLN grosze (1/100)
  category: ProductCategory;
  collection: string;
  /** Primary photo — convenience alias for `images[0]`. */
  image: string;
  /** Full photo set (real product photography). Always at least one entry. */
  images: string[];
  description: LocalizedString;
  sizes: string[];
  /** Per-size remaining inventory, e.g. `{ "36": 5, "38": 2 }`. 0 = that size sold out. */
  stockBySize: Record<string, number>;
  featured?: boolean;
  newArrival?: boolean;
  /** Fibre composition / material copy, bilingual. */
  materials?: LocalizedString;
  /** Primary colour name, bilingual. */
  color?: LocalizedString;
  /**
   * Cached total across all sizes. Derived from `stockBySize` (sum) — present so
   * legacy callers and admin metrics that read a single number keep working.
   * `undefined` means unknown (treated as in-stock).
   */
  stockQuantity?: number;
}

export interface BlogPost {
  id: string;
  slug: string;
  title: LocalizedString;
  excerpt: LocalizedString;
  image: string;
  date: string;
  author: string;
  body: BlogBlock[];
}

export interface Collection {
  id: string;
  name: string;
  slug: string;
  image: string;
  description: LocalizedString;
}

// ─── Catalog (collections + products) ────────────────────────────────────────
//
// The live catalog mirrors the real absolutdimension.com storefront and is
// generated by scripts/ingest-absolutdimension.ts (run `npm run ingest`). It is
// emitted to ./catalog.generated.ts; we re-export it here so the rest of the app
// keeps importing `collections` / `products` from "../lib/data" unchanged.

export const collections: Collection[] = generatedCollections;

export const products: Product[] = generatedProducts;

// ─── Blog Posts ──────────────────────────────────────────────────────────────

// "The Art of Refined Dressing" — the brand's real journal.
export const blogPosts: BlogPost[] = [
  {
    id: "b1",
    slug: "s-i-l-e-n-t",
    title: { en: ". S i l e n t .", pl: ". C i s z a ." },
    excerpt: {
      en: "Silence is where you are born — the right one. You don’t have to scream; what is yours simply flows out.",
      pl: "Cisza to miejsce, w którym się rodzisz — ta właściwa. Nie musisz krzyczeć; to, co Twoje, po prostu wypływa.",
    },
    image: "/img/blog/blog-1.jpg",
    date: "2026-03-15",
    author: "Absolut Dimension",
    body: blogBodies["s-i-l-e-n-t"],
  },
  {
    id: "b2",
    slug: "life-is-about-style",
    title: { en: ". LIFE is about STYLE .", pl: ". ŻYCIE jest o STYLU ." },
    excerpt: {
      en: "Our dreams are worthy. Our value is meaningful. Style begins the moment you stop asking for approval.",
      pl: "Nasze marzenia są wartościowe. Nasza wartość ma znaczenie. Styl zaczyna się w chwili, gdy przestajesz pytać o akceptację.",
    },
    image: "/img/blog/blog-2.png",
    date: "2026-02-20",
    author: "Absolut Dimension",
    body: blogBodies["life-is-about-style"],
  },
  {
    id: "b3",
    slug: "journey-droga-do-siebie",
    title: { en: "Journey . The Way to Yourself", pl: "Journey . Droga do siebie" },
    excerpt: {
      en: "SM.ART Wardrobe — Winter in Paris. The same wardrobe, eight lives: walking, the library, Café de Flore, the Hemingway Bar.",
      pl: "Garderoba SM.ART — Zima w Paryżu. Ta sama garderoba, osiem żyć: spacer, biblioteka, Café de Flore, Hemingway Bar.",
    },
    image: "/img/blog/blog-3.jpg",
    date: "2026-01-18",
    author: "Absolut Dimension",
    body: blogBodies["journey-droga-do-siebie"],
  },
  {
    id: "b4",
    slug: "womenworld",
    title: { en: ". WomenWorld .", pl: ". WomenWorld ." },
    excerpt: {
      en: "A woman creates, produces, begets — she stands in true power. A personal letter that begins with dresses knitted by hand in Africa.",
      pl: "Kobieta tworzy, wytwarza, rodzi — stoi w prawdziwej sile. Osobisty list, który zaczyna się od sukienek dzierganych ręcznie w Afryce.",
    },
    image: "/img/blog/blog-4.png",
    date: "2025-12-12",
    author: "Absolut Dimension",
    body: blogBodies["womenworld"],
  },
  {
    id: "b5",
    slug: "sztuka-spojnosci-total-look",
    title: { en: "The Art of Coherence = TOTAL LOOK", pl: "Sztuka spójności = TOTAL LOOK" },
    excerpt: {
      en: "In luxury, consistency isn’t a limitation — it’s a strength. Dress, accessories, jacket and jewellery answering to one idea.",
      pl: "W luksusie spójność nie jest ograniczeniem — jest siłą. Sukienka, dodatki, żakiet i biżuteria odpowiadające jednej idei.",
    },
    image: "/img/products/38-sukienka-paris/0.webp",
    date: "2025-11-28",
    author: "Absolut Dimension",
    body: blogBodies["sztuka-spojnosci-total-look"],
  },
  {
    id: "b6",
    slug: "doha",
    title: { en: "Packing — the Nightmare of Travel", pl: "Pakowanie — koszmar podróży" },
    excerpt: {
      en: "There is no emergency closet on the road. The anxiety of the suitcase is exactly what led to the SM.ART Wardrobe.",
      pl: "W podróży nie ma awaryjnej szafy. To właśnie lęk przed walizką doprowadził do Garderoby SM.ART.",
    },
    image: "/img/products/15-sukienka-paradajsu-1/0.webp",
    date: "2025-11-10",
    author: "Absolut Dimension",
    body: blogBodies["doha"],
  },
];

// ─── Category labels (bilingual) ─────────────────────────────────────────────

export const categoryLabels: Record<ProductCategory, LocalizedString> = {
  dress:    { en: "Dresses",    pl: "Sukienki" },
  coat:     { en: "Coats",      pl: "Płaszcze" },
  bag:      { en: "Bags",       pl: "Torebki" },
  set:      { en: "Sets",       pl: "Komplety" },
  skirt:    { en: "Skirts",     pl: "Spódnice" },
  top:      { en: "Tops",       pl: "Topy" },
  blazer:   { en: "Blazers",    pl: "Żakiety" },
  kimono:   { en: "Kimonos",    pl: "Kimona" },
  scarf:    { en: "Scarves",    pl: "Szale" },
  pants:    { en: "Trousers",   pl: "Spodnie" },
  cardigan: { en: "Cardigans",  pl: "Kardigany" },
  poncho:   { en: "Ponchos",    pl: "Ponczo" },
  body:     { en: "Bodysuits",  pl: "Body" },
  blouse:   { en: "Blouses",    pl: "Bluzki" },
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Format a price stored in PLN grosze as a locale-aware string:
 *   pl → "2 800 zł"
 *   en → "2,800 zł"
 *
 * Currency suffix stays "zł" in both languages — the brand sells exclusively
 * in PLN and a customer using the English UI is still seeing a Polish price.
 */
export function formatPrice(priceInGrosze: number, locale: "pl" | "en" = "pl"): string {
  const zloty = Math.round(priceInGrosze / 100);
  const intlLocale = locale === "pl" ? "pl-PL" : "en-GB";
  const formatted = zloty.toLocaleString(intlLocale).replace(/\u00A0/g, " ");
  return `${formatted} zł`;
}

export function getProductsByCollection(slug: string): Product[] {
  return products.filter((p) => p.collection === slug);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function getNewArrivals(): Product[] {
  return products.filter((p) => p.newArrival);
}

export function getProduct(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getCollection(slug: string): Collection | undefined {
  return collections.find((c) => c.slug === slug);
}

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}
